<?php
/**
 * @file
 * toolshed_browse.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function toolshed_browse_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-6S5wpE0cK7z7jYNwqphrA1jmTGH8C7Bb'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => '6S5wpE0cK7z7jYNwqphrA1jmTGH8C7Bb',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'browse/programs',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'toolshed',
        'weight' => -36,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['facetapi-Ew8gdR5YB9GZmLZqbI28GbKa7flcsxmz'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'Ew8gdR5YB9GZmLZqbI28GbKa7flcsxmz',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'browse/resources
browse/presentations',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'toolshed',
        'weight' => -37,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['facetapi-Nei9k1pkBblurMjjnV2seIeqy8NR02PE'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'Nei9k1pkBblurMjjnV2seIeqy8NR02PE',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'browse/presentations',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'toolshed',
        'weight' => -40,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['facetapi-bwSt4KPUHR6OZhVMiQDGZQVGOMJQgqOZ'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'bwSt4KPUHR6OZhVMiQDGZQVGOMJQgqOZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'browse/programs',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'toolshed',
        'weight' => -35,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['facetapi-ny4PB36Xs6ldCAeg9re47Hrv16bhoBF2'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'ny4PB36Xs6ldCAeg9re47Hrv16bhoBF2',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'browse/presentations',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'toolshed',
        'weight' => -39,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['facetapi-pmJDx1bktrlXOUOvk3dmJ2Nzuf1mXpaZ'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'pmJDx1bktrlXOUOvk3dmJ2Nzuf1mXpaZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'browse/presentations
browse/programs
browse/resources',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'toolshed',
        'weight' => -34,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  $export['facetapi-szkopraY3UT0Yf7W9c45i0Uff9eQnJxP'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'szkopraY3UT0Yf7W9c45i0Uff9eQnJxP',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'toolshed',
        'weight' => -40,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-vthVBf2pBg6rowsRhv5hELOdXMWH1yXC'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'vthVBf2pBg6rowsRhv5hELOdXMWH1yXC',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'toolshed',
        'weight' => -41,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-yAft0GXXM1GQg0Zk8oUWQxAHub2CMkGv'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'yAft0GXXM1GQg0Zk8oUWQxAHub2CMkGv',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'toolshed',
        'weight' => -42,
      ),
    ),
    'title' => '<none>',
    'visibility' => 0,
  );

  $export['facetapi-yI3Qwke4KC40mDKP1efzWWV5thRP6CKx'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'yI3Qwke4KC40mDKP1efzWWV5thRP6CKx',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'browse/resources',
    'roles' => array(),
    'themes' => array(
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
      'toolshed' => array(
        'region' => 'content',
        'status' => 1,
        'theme' => 'toolshed',
        'weight' => -38,
      ),
    ),
    'title' => '<none>',
    'visibility' => 1,
  );

  return $export;
}
